branches:
  only:
    - master
language: node_js
node_js:
  - 14
#cache:
#  directories:
#   - node_modules
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: npm
  email: "amitrajput123.ar@gmail.com"
  api_key: $npm_token
  local_dir: dist
  on:
    branch: master