branches:
  only:
    - master
language: node_js
node_js:
  - 16
#cache:
#  directories:
#   - node_modules
install:
  - pnpm install
script:
  - pnpm buildall
deploy:
  - provider: npm
    email: $email
    api_key: $npm_token
    local_dir: dist
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
      github_token: $github_token
      local_dir: example/dist
      on:
        branch: main